version: '3.8'

services:
  postgres:
    image: postgres
    container_name: postgres_container
    networks:
      - keycloak-network
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    platform: linux/amd64

  keycloak:
    image: keycloak/keycloak:25.0.0
    container_name: keycloak_container
    networks:
      - keycloak-network
    environment:
      DB_VENDOR: postgres
      DB_ADDR: postgres
      DB_PORT: 5432
      DB_DATABASE: postgres
      DB_USER: admin
      DB_PASSWORD: admin
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
#      use these parameters if your keycloak version is 26.x.x
#      KC_BOOTSTRAP_ADMIN_USERNAME: admin
#      KC_BOOTSTRAP_ADMIN_PASSWORD: admin

    ports:
      - "8080:8080"
    platform: linux/amd64
    command: start-dev

networks:
  keycloak-network:
    driver: bridge